### ISSUE TITLE
Is this plugin still supported?

### ISSUE THREAD

**Issue by bartkl** [coderbuzz/bottle-peewee#1]
Hi,

It seems the bottle-peewee plugin is no longer in the bottle-extras plugin meta package. Is this plugin still supported and actively developed?

A question on the side: is it Python 3 compatible?

Thank you!
Bart

P.S.: Usually I wouldn't have created an issue ticket for this, but since there's no contact info whatsoever it's pretty much the only way of contacting you I could think of.

**Comment by coderbuzz** [comment]
Hi, this plugin is not supported anymore. Thanks
